tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr1.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr2.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr3.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr4.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr5.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr6.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr7.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr8.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr9.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr10.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr11.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr12.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr13.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr14.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr15.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr16.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr17.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr18.vcf.gz
tabix -p vcf /media/uni/data/projects/population_data/18.new_vcf/06.fd/01.vcf/populus_chr19.vcf.gz
